-- ============================================================================
-- Schedule_Portal — seed cities -> region (G1.10). Run once in the SQL Editor,
-- after 0009_cities.sql. Idempotent (ON CONFLICT DO NOTHING); re-runnable.
-- AREA mapping: North->north, South->south, St George->st_george, Out Of State->another.
-- Kept intentional spelling variants (St George / St. George / Saint George, SLC,
-- Milkreek, Gerantsville, ...) so messy client-portal city strings still match.
-- ============================================================================
insert into schedule_portal.cities (organization_id, name, region)
select o.id, v.name, v.region::schedule_portal.region
from schedule_portal.organizations o
cross join (values
  ('Lehi','south'),
  ('Draper','south'),
  ('Bluffdale','south'),
  ('Riverton','south'),
  ('Cottonwood Heights','north'),
  ('Salt Lake City','north'),
  ('Midvale','north'),
  ('Cedar City','st_george'),
  ('Utah County','south'),
  ('Saratoga Springs','south'),
  ('Eagle Mountain','south'),
  ('South Jordan','north'),
  ('Park City','north'),
  ('West Jordan','north'),
  ('American Fork','south'),
  ('Heber City','south'),
  ('West Valley City','north'),
  ('Syracuse','north'),
  ('Millcreek','north'),
  ('Riverdale','north'),
  ('Herriman','south'),
  ('Pleasant Grove','south'),
  ('Payson','south'),
  ('Salem','south'),
  ('Spanish Fork','south'),
  ('Mapleton','south'),
  ('Orem','south'),
  ('West Haven','north'),
  ('Ogden','north'),
  ('Sandy','north'),
  ('Eden','north'),
  ('Murray','north'),
  ('Kearns','north'),
  ('Bountiful','north'),
  ('Clearfield','north'),
  ('Layton','north'),
  ('Clinton','north'),
  ('Salt Lake County','north'),
  ('Taylorsville','north'),
  ('Sugarhouse','north'),
  ('Springville','south'),
  ('Highland','north'),
  ('Altamont','south'),
  ('Tooele','north'),
  ('Oljato-Monument Valley','st_george'),
  ('St. George','st_george'),
  ('West Valley','north'),
  ('Springfield','another'),
  ('Holladay','north'),
  ('Washington','st_george'),
  ('Provo','south'),
  ('Cedar Hills','south'),
  ('Farmington','north'),
  ('Magna','north'),
  ('Alpine','south'),
  ('Fairfield','north'),
  ('Cedar Fort','south'),
  ('Saint George','st_george'),
  ('West Point','north'),
  ('North Ogden','north'),
  ('Kaysville','north'),
  ('Washington County','st_george'),
  ('Hurricane','st_george'),
  ('Wood Cross','north'),
  ('Huntsville','north'),
  ('Fairview','south'),
  ('Elk Ridge','south'),
  ('North Salt Lake','north'),
  ('South Salt Lake','north'),
  ('Weber County','north'),
  ('Evanston','another'),
  ('Mountain Green','north'),
  ('Morgan','north'),
  ('Kamas','south'),
  ('Roy','north'),
  ('Logan','north'),
  ('Midway','north'),
  ('Perry','north'),
  ('Price','south'),
  ('Santaquin','south'),
  ('Hideout','north'),
  ('Santa Clara','st_george'),
  ('Woods Cross','north'),
  ('St George','st_george'),
  ('Toquerville','st_george'),
  ('Virgin','st_george'),
  ('Springdale','st_george'),
  ('Haven','north'),
  ('Centerville','north'),
  ('Lindon','south'),
  ('Davis County','north'),
  ('Coalville','north'),
  ('Heber','south'),
  ('Milkreek','north'),
  ('Grantsville','north'),
  ('Stansbury Park','north'),
  ('Erda','north'),
  ('Stansbury Place','north'),
  ('Pleasant View','north'),
  ('Gerantsville','north'),
  ('Cache County','north'),
  ('Daniel','south'),
  ('Wasatch County','south'),
  ('Saratoga Springs UT','south'),
  ('SLC','north'),
  ('Moab','north'),
  ('Hill Air Force Base','north'),
  ('Farr West','north'),
  ('Plain City','north'),
  ('Snowbird','north'),
  ('West Point,','north'),
  ('Vineyard','south'),
  ('Bellevue','south'),
  ('South Ogden','north'),
  ('Chubbuck','another'),
  ('Cottonwood','north'),
  ('Ivins','st_george'),
  ('Harrisville','north'),
  ('Brigham City','north'),
  ('Willard','north'),
  ('Lake Point','north'),
  ('Taylor','north'),
  ('Carbondale','another'),
  ('Woodland Hills','south'),
  ('Uintah','north'),
  ('Kemmerer','another'),
  ('Marriott-Slaterville','north'),
  ('Vernal','south'),
  ('Delta','another'),
  ('Spring Creek','another'),
  ('Naples','north'),
  ('Phoenix','another'),
  ('Brighton','north'),
  ('Peoa','north'),
  ('Fruit Heights','north'),
  ('South Weber','north'),
  ('Plesant Grove','south'),
  ('Fish Haven','another'),
  ('St. Salt Lake','north')
) as v(name, region)
where o.slug = 'delta-pro-clean'
on conflict (organization_id, lower(name)) do nothing;
